spring:
  data:
    mongodb:
      database: test
      uri: mongodb+srv://${MONGODB_URI}/?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        kerberos:
          service:
            name: kafka
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
    consumer:
      group-id: ${KAFKA_USERNAME}-consumers
